services:
  php_mail:
    build:
      dockerfile: Dockerfile
    container_name: mail_service
    networks:
      - ci4_network
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
    expose:
      - "8080"
    ports:
      - "7000:8080"
    command: >
      bash -c "apt-get update &&
      apt-get install -y libicu-dev &&
      apt-get install -y libpq-dev &&
      apt-get install -y git &&
      docker-php-ext-install intl &&
      docker-php-ext-install pgsql &&
      php spark migrate &&
      php spark serve --host 0.0.0.0 --port 8080"

  db_mail:
    image: postgres:13
    container_name: mail_db
    environment:
      POSTGRES_USER: ${DB_USERNAME} # Use the DB_USERNAME from .env
      POSTGRES_PASSWORD: ${DB_PASSWORD} # Use the DB_PASSWORD from .env
      POSTGRES_DB: ${DB_DATABASE} # Use the DB_DATABASE from .env
    volumes:
      - mail_data:/var/lib/postgresql/data
    networks:
      - ci4_network

volumes:
  mail_data:

networks:
  ci4_network:
    driver: bridge
