services:
  php_mail:
    image: php:8.1-fpm
    container_name: ci4_php_fpm
    volumes:
      - ./Service:/var/www/html:z # Bind mount your CI4 code to the container
    networks:
      - ci4_network
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
    expose:
      - "8080"
    ports:
      - "9000:8080"
    command: >
      bash -c "apt-get update &&
      apt-get install -y libicu-dev &&
      apt-get install -y libpq-dev &&
      apt-get install -y git &&
      docker-php-ext-install intl &&
      docker-php-ext-install pgsql &&
      php spark serve --host 0.0.0.0 --port 8080"

  db_mail:
    image: postgres:13
    container_name: ci4_postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME} # Use the DB_USERNAME from .env
      POSTGRES_PASSWORD: ${DB_PASSWORD} # Use the DB_PASSWORD from .env
      POSTGRES_DB: ${DB_DATABASE} # Use the DB_DATABASE from .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ci4_network

volumes:
  postgres_data:

networks:
  ci4_network:
    driver: bridge
